name: Build and Deploy
on:
  push:
    branch:
      - main
  workflow_dispatch:


permission:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-lastest
    steps:
      - name: checkout
        uses: action/checkout@v3
      
      - name: Install and Build
        run: 
          npm ci
          npm run build


      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/angular-app
      